### ISSUE TITLE
Synced lyrics for playlist as zip add this feature sir.

### ISSUE THREAD

**Issue by ItsMohammedaamir** [akashrchandran/syrics-web#1]
![Screenshot_2023-03-03-12-23-00-48_2c2851f616de21a6da6fb44c83a25e93](https://user-images.githubusercontent.com/116973976/222651993-17f04e90-0c2a-470a-88f4-dacd53ec04b3.jpg)
You are God sir . You made impossible to possible 🔥.
@akashrchandran 

🔥
But zip feature is not available for playlist . When I click on zip file it stuck & loading .
Please add this feature  sir, ....🫡

Thank you
All the features working correctly
I really appreciate your work.

**Comment by ItsMohammedaamir** [comment]
![Uploading Screenshot_2023-03-03-12-23-00-48_2c2851f616de21a6da6fb44c83a25e93.jpg…]()

**Comment by akashrchandran** [comment]
@ItsMohammedaamir I have fixed it, if find anything more than please open a new issue.

**Comment by ItsMohammedaamir** [comment]
Thank you sir .

**Comment by ItsMohammedaamir** [comment]
🔥Fixed🔥
