### ISSUE TITLE
Some of the Spotify album Link is not recognised.

### ISSUE THREAD

**Issue by iammohammedaamir** [akashrchandran/syrics-web#11]
Some Spotify links have lyrics but syrics don't Identified them & says no lyrics found. I have seen this problem before & I also open a issue In may or June . I think this is the problem with Spotify updated link. Please resolve this issue.

Example album links:

https://open.spotify.com/album/0UuTH5r9tyFJ2tqnvc1wWm?si=J_Z2xExURgeVrWN91NxLig&context=spotify%3Aalbum%3A0UuTH5r9tyFJ2tqnvc1wWm

https://open.spotify.com/album/2zkyMw73XzNXUQaXTb4cio?si=-rfeRyAIS_WfEvWxIa8aWw&context=spotify%3Aalbum%3A2zkyMw73XzNXUQaXTb4cio

https://open.spotify.com/album/5OLQiL6HaWJl734EqPjoY9?si=PV4V5WCGSe2nfVpBPgKytg&context=spotify%3Aalbum%3A5OLQiL6HaWJl734EqPjoY9

**Comment by akashrchandran** [comment]
My Spotify lyrics API is having issues due to too many requests. Please try again, and it should work fine! You may have to try more than twice for it to work 😅.

**Comment by iammohammedaamir** [comment]
Yes I will check it it will be fine thanks you sir .
I have suggestions if you add itune lyrics grabber if possible you will
reach more people. Both of the  sites are use musixmatch api. Think if it
is possible  only a suggestion King👑. 🥳
