### ISSUE TITLE
Unable to download lyrics link issue.

### ISSUE THREAD

**Issue by iammohammedaamir** [akashrchandran/syrics-web#12]
Spotify lyrics are only for premium user now so we can't download any lyrics from syrics plz update the script or add a itune link features plz sir.

[Selena Gomez ( Deluxe Album)](Album • Selena Gomez https://open.spotify.com/album/5obQ9rPASQW2mLxYM8Ko6Z) 
![Screenshot_2023-09-24-11-44-16-55_305a1a3985c21ffed1ac8d6efbd1fa75](https://github.com/akashrchandran/syrics-web/assets/116973976/417fef15-097a-46dc-8d7d-6fad12b9d4d4)

> Plz resolved this issue. Or please add itune link support to syrics .

**Comment by akashrchandran** [comment]
iTunes isn't the way to go—it also requires a premium account or at least a trial. 🙅‍♂️ Hey, if you've been keeping up with me, you probably saw me attempting to create one, but I hit a roadblock with the whole premium account thing. If you've got one, feel free to drop the details, and I'll take a shot at getting it up and running. 🚀.

https://github.com/akashrchandran/apple-lyrics-api

**Comment by iammohammedaamir** [comment]
Spotify is now back the decision of lyrics. LRC lyrics is back again slowly for some albums. I think they block the lyrics of Hollywood album.⭐

**Comment by iammohammedaamir** [comment]
Once again legend fix the problem
