### ISSUE TITLE
Doesnt fetch lyrics

### ISSUE THREAD

**Issue by GitHubBob00** [akashrchandran/syrics-web#13]
It gives me an error when. Clock download zip saying that none of my songs have lyrics even when they do when I play normally through spotify

**Comment by iammohammedaamir** [comment]
Same problem. When Spotify published lyrics under premium subscription bot is not able to download anything.

**Comment by akashrchandran** [comment]
The app's back, but not all song lyrics are available. Check the comments for more info!

https://github.com/akashrchandran/spotify-lyrics-api/issues/26#issuecomment-1742167876

**Comment by iammohammedaamir** [comment]
Syrics is not fetching lyrics If song have lyrics available. I tried after sometime but it doesn't give lyrics for example if album have 20 songs it gives only 10 song lyrics everytime when I try . Plz fix this I see this month syrics have some bugs seen.
