### ISSUE TITLE
Stuck on Orbiting Dots

### ISSUE THREAD

**Issue by cdh31211811** [akashrchandran/syrics-web#15]
Instead of saying "No lyrics found", the download button is now perpetually stuck at the loading stage with orbiting dots. It gets stuck like this for many hours, even days, with no download. Tried with different Spotify songs that have lyrics.

**Comment by akashrchandran** [comment]
Please give the links you tried, so I can recreate the issue.

**Comment by cdh31211811** [comment]
Hi Akash,

I really don't think it depends on the link. But you can try:
https://open.spotify.com/track/0J1kF6VdorvmLjmRJObiV1
https://open.spotify.com/album/36bEg6FTBaZGLg9ngJZIU6
https://open.spotify.com/track/4SR6nkvrIYl05tvg7Flsfa

Actually, songs with no lyrics end up with the same orbiting dots as well:
https://open.spotify.com/track/273dCMFseLcVsoSWx59IoE?si=490f7c16f4654fd3

Thanks,
Clark H.

**Comment by akashrchandran** [comment]
It seems to work fine on my end. I've tested it on multiple devices. Could you please share the console output? If you're unfamiliar with browser developer tools, you can follow the steps below.

![chrome_BxtwgStwXj](https://github.com/akashrchandran/syrics-web/assets/78685510/0fdb1efa-6c75-413b-bd84-114a1fdd5de3)

**Comment by akashrchandran** [comment]
No reply, so closing the issue. If anyone is experiencing the same problem, please open a new issue.

**Comment by cdh31211811** [comment]
I'm sorry I got super busy. I'll open a new issue when I get the chance.
Thanks.
