### ISSUE TITLE
No lyrics found

### ISSUE THREAD

**Issue by namikazeloves** [akashrchandran/syrics-web#19]
Can't download or batch download .lrc file even though it has a sync lyrics on the app. It says "No lyrics found" on the site. Hope this will fix soon.

**Comment by akashrchandran** [comment]
The problem is that many song lyrics on Spotify require a Premium subscription, which I currently don't have. If you're willing, you could donate, or if you happen to have an extra Premium account, you could share it with me, and I can integrate it into the app.
