### ISSUE TITLE
"No lyrics found" though there definitely are

### ISSUE THREAD

**Issue by Supershunn** [akashrchandran/syrics-web#22]
To recreate this bug, paste "https://open.spotify.com/album/7GJtALMajef2QQw7cyzXyx?si=99oZyn2-R566MCWAbQPIzg", and try to download "Yume no Sotohe" and "Film". They don't work but the rest works just fine. Those two specifically just returns "No lyrics found." I tried it multiple times.

**Comment by akashrchandran** [comment]
Likely restricted to specific regions. The Syrics website relies on a US account for lyrics access. Attempt downloading with your own account using the command line version available at https://github.com/akashrchandran/syrics.
