### ISSUE TITLE
lyrics for some songs takes forever to download

### ISSUE THREAD

**Issue by FSint653** [akashrchandran/syrics-web#25]
Its works fine as usual but for some songs it takes forever to start downloading the lyrics even though that song has synced lyrics available on Spotify. at the same time if I am downloading some other song's lyrics in another tab it will download smoothly 

Song link that I last checked few seconds ago not working
https://open.spotify.com/track/2lX53kXvYnvpV8Vqfe4S7s?si=d5cfba1cebf6447a
Screenshot
<img width="1389" alt="Screenshot 2024-04-03 at 6 50 38 AM" src="https://github.com/akashrchandran/syrics-web/assets/57948707/3dda3741-068f-4d53-bf12-5ec235726fdf">

**Comment by akashrchandran** [comment]
This happens when the lyrics are not available, I have fixed it show bage when not available in commit  https://github.com/akashrchandran/syrics-web/commit/5ff8e1f134ddddb4c384f61313672af6770b054b.
