### ISSUE TITLE
Lyrics can't be downloaded 

### ISSUE THREAD

**Issue by UDITRAJMG2006** [akashrchandran/syrics-web#28]
https://open.spotify.com/track/4T4n4gSb8ngJ8ISXyAdt0x?si=unozEIkaQEe_L0e1IWluKA

This is the lyrics I was trying to download but it isn't working
![Uploading Screenshot_2024-07-20-13-48-41-502_com.android.chrome.jpg…]()

**Comment by akashrchandran** [comment]
It clearly says no lyrics found. Either there is no lyrics available in Spotify or It is not available in US region. If you have premium account of spotify you can try downloading using the [syrics](https://github.com/akashrchandran/syrics).
