### ISSUE TITLE
Very Big issue Syrics not able to recognise any Spotify links. 

### ISSUE THREAD

**Issue by ItsMohammedaamir** [akashrchandran/syrics-web#5]
I don't test all playlists songs download issue is fixed or not because there is NEW big issue in syrics i.e 
SYRICS was not able to recognise any Spotify links.
Any playlist link
Any albums link
Or any songs link
Kindly fixed this error. 

✅Tested on mobile Realme Gt Master Edition

Very big issue sir.

Video 🔗 https://gofile.io/d/n99Xdi

**Comment by ItsMohammedaamir** [comment]
#

https://user-images.githubusercontent.com/116973976/224913018-0e48e988-2cbe-4d49-af72-f8103184521e.mp4

**Comment by akashrchandran** [comment]
May I ask where you got these types of links, I have never encountered this type of link that's why I never added support for that. I have only added support for open.spotify.com links and Spotify URI.

**Comment by ItsMohammedaamir** [comment]
I will found this link on Spotify app.

**Comment by akashrchandran** [comment]
Could you please send me the links. So that I can test it and will add support for that.

**Comment by ItsMohammedaamir** [comment]
Okay sir, I also don't what the kind of this links I think Spotify changed thier links may be. 

I will send some of them

**Comment by ItsMohammedaamir** [comment]
Links
[Spotify @ Test links .pdf](https://github.com/akashrchandran/syrics-web/files/10978248/Spotify.%40.Test.links.pdf)

**Comment by ItsMohammedaamir** [comment]
Zip file does not extract in my device ?
Exception while decompress file

**Comment by akashrchandran** [comment]
> I will give Some of links here [Spotify @ Test links .pdf](https://github.com/akashrchandran/syrics-web/files/10978297/Spotify.%40.Test.links.pdf)

Thanks for sharing the example links. I have worked out a way to add support for this type of urls but I am not sure if they will work flawlessly. If you find any bugs do report them.

Thank you

**Comment by akashrchandran** [comment]
> Zip file does not extract in my device ? Exception while decompress file

Did you try downloading again? If it still doesn't wokr than please raise the issue here and also attach the link you have used.

Happy to help!

**Comment by ItsMohammedaamir** [comment]
🔥Akash sir 💥
 had been fixed all the Issues & bugs associate with syrics. Now all the Spotify links work successfully.
Thank you so much sir.

Some time when I click on download option download doesn't start.
Zip doesn't directly extract in my device with any of its file explorer until when I download RAR app from Play Store. When you are becoming free please fix this . I did not open any new issue.

Once again thank you sir for solve my issues.
